poljar/weechat-matrix

matrix/rooms.py
matrix/utils.py

When room names that were previously set get deleted, the server still
returns the name key, but set to the value of an empty string. Handle
this case as if there is no room name.

Fix handling of empty room names.

---

matrix/bar_items.py
matrix/commands.py
matrix/rooms.py

We now track the room ID, the canonical alias and the name of the room
separately. Only the room ID is guaranteed to be set (instead of `None`).
Additionally, a number of methods were added to MatrixRoom to assist in
calculating the name of the room and determining whether it is a named room
or an ad hoc "group" of users.
The most important method is `MatrixRoom.display_name` which calculates the
display name of the room (roughly) according to section 11.2.2.5[*] of the
Matrix v0.3.0 spec.
[*] https://matrix.org/docs/spec/client_server/r0.3.0.html#id268

Improve room names.

---

matrix/colors.py
matrix/rooms.py
tests/color_test.py

Strikethrough has to be done first, before handling any other attribute,
because otherwise it doesn't render correctly.
The following changes were made:
1. When striking due to redaction, we simply strip all the other
attributes and then do the strikethrough, because this is the only
practical option.
2. When rendering rich text received from the server, we ensure we
handle strikethrough first, before any other attribute.

Handle combination of strikethrough and other attributes.

---

matrix/colors.py
tests/http_parser_test.py

Forgot to include # when reconstructing charrefs from their "name".

Fix charrefs.

---

matrix/colors.py

Always append the last segment of the message with default attributes.
This prevents unclosed Markdown delimiters from starting Markdown
effects (for instance, `*foobar` won't display "foobar" as
emphasized/italicised).
Markdown parsing is still half-broken as it isn't a proper Markdown
parser, but this improves the situation somewhat.

Fix parsing of unclosed Markdown delimiters.

---

README.md

The default matrix server is named matrix_org instead of matrix.org.
This is a great plugin all the matrix clients were far resource heavy for my liking and was already using weechat, Cheers :smile:

Fix Configuration instructions in readme

---

main.py

If the server doesn't support ALPN or NPN, negotiated_protocol will be
None. That meant that transport_type wouldn't be set, in which case nio
will raise a NotImplementedError. Instead, set transport_type to HTTP if
nothing is negotiated.

Fallback to HTTP1 when HTTP2 is not negotiated

---

matrix/bar_items.py

This fixes the values returned for the bar items for buffers not belonging to matrix so they are identical to the values used when matrix is not loaded.
This fixes the part of #54 about wrong values, but the issue that multiple scripts can't do this still remains. I've asked about it in #weechat on freenode, but not received any answer yet.

Fix bar items contents for other buffers

---

README.md

The list of dependencies in the README was out of sync with the list in requirements.txt since weechat-matrix now requires e2ee support in matrix-nio. Opening requirements.txt and installing dependencies manually is either trivial to those who know python packaging or provides no benefit to those who do not. Removing this list reduces maintenance effort and does not make installation harder to understand.

Remove list of dependencies from README

---

contrib/matrix_upload

Use full path instead of basename when reading file for upload

---

README.md
main.py

This PR adds support for running dependencies from a virtualenv. This is done by autodetecting the presence of a `venv` directory and including the `activation_this.py` script in there. See the updated README for details.
Additionally, it documents what `make install` does, which is often a thing I wonder in these cases.
Finally, it documents how you can set up symlinks rather than using make install to run directly from git. I investigated how to do this without symlinks (just cloning into `~/.weechat/python/weechat-matrix` and then running `/script load weechat-matrix/main.py`, but I couldn't make that work without modifying `sys.path` from inside `main.py` to make `import matrix` work, and that seemed a bit too invasive for now). If you're interested, maybe we could think of a nicer …

Support virtualenv and symlinking

---

matrix/_weechat.py
matrix/config.py
matrix/server.py

```
13:37 julius Hm, any way to limit the maximum reconnect delay?
16:56 &poljar the initial one? yes, as it grows, sadly not yet
18:33 <julius> as it grows. I amassed a 3 or so hour reconnect delay because I kept turning on my notebook only for a short time, and the first connect after resume-from-suspend always fails because wpa_supplicant is a slowpoke.
18:34 <&poljar> there's no way to limit it yet, but it would be fairly easy to add
18:51 <julius> I hope I have time this weekend…
…
14:56 <julius> Hm, if I add a maximum reconnect delay, should that be a server config property or just under network?
17:02 <&poljar> it's under network for the irc plugin, so i would say under network
```

Add options for controlling reconnect delay growth

---

matrix/buffer.py

Oh well, display names everywhere would be much nicer but meanwhile the if block needs some enlargement because some instances of Telegram bridges use `_telegram` prefix instead of `telegram`.

Some Telegram bridges use "_telegram" prefix instead of plain "telegram"

---

matrix/_weechat.py
matrix/buffer.py
matrix/config.py

Fixes #61
Wish list / things that [`irc-channel.c`](https://github.com/weechat/weechat/blob/a843e8fb1434385b923cbc9d09bbc50a98c98ca7/src/plugins/irc/irc-channel.c#L74-L122) doesn't do:

Add new_channel_position config option

---

contrib/matrix_upload

`matrix_upload` and `matrix_decrypt` incorrectly had the same description.

fix matrix_upload description

---

matrix/buffer.py

My room list loads nicely when I connect to Matrix for the first time. But when I connect for the second time, I get the following error and the room list does not load:
I found out it happened because buffer names were being set to `None`. I was able to fix this by adding a placeholder name. Now rooms get the name `"..."`, and a few seconds later, as more events are received from the server, they change to their actual names.

placeholder room name

---

README.md

Most people don't have a new enough version, so the required version should be more explicit.

Specify what "new enough" debian/ubuntu means

---

requirements.txt

If nio 0.9 is installed, the build fails for python 2.7. Unfortunately you're not able to change the used python version in weechat. This change should stay until all stable systems are using python3 as default.
Worked for me with `pip install matrix-nio[e2e]==0.6`.

matrix-nio == 0.6

---

README.md

It might be easy to miss that you can't have them installed with the suffix, and then causes errors alike #83

Added clarification on instalation of helper scripts

---

matrix/commands.py

When passing arguments to format error messages for `/olm verification`, the order of device id and user id has been swapped, leading to confusing messages. Let's restore the correct order.

commands: fix user/device ids in error messages for "/olm verification"

---

matrix/commands.py

Typing `/olm` on its own is supposed to fall back to the default subcommand `/olm info private`. It does pick up `info`, but fails to find a `category` (in our case: we want `private`) because the category has never been parsed, and has never been assigned to `args`. Not only does the command fail, but it even yields a traceback:
python : stdout/stderr (matrix) : Traceback (most recent call last):
python : stdout/stderr (matrix) :   File "/home/qmo/weechat/conf/python/matrix/utf.py", line 89, in wrapper
python : stdout/stderr (matrix) :     return function(*args, **kwargs)
python : stdout/stderr (matrix) :   File "/home/qmo/weechat/conf/python/matrix/commands.py", line 891, in matrix_olm_command_cb
python : stdout/stderr (matrix) :     return command(server, data, buffer, args)
python : …

commands: prevent python crash when typing simply "/olm"

---

matrix/colors.py
matrix/config.py

This adds a config option to change (or disable) the automatic soft-wrapping width of blockquotes.
Rationale: my terminal is fairly wide, and the default of 67 chars looks fairly stupid in it.
Note that the default of 67 chars is unchanged by this PR: if the user doesn't change the config option, there should be no visible change in behaviour.
I'm not sure about the `textwrapper()` method on the `Formatted` class; it didn't use `self` before, and still doesn't, and was only used in one place. Anyway, I left it mostly the same as it was, though I made it a proper method instead of a `@property` because I wanted to pass some arguments.

Add quote_wrap option

---

matrix/colors.py
tests/color_test.py

This fixes some issues with the current semi-markdown-parser. I know there is a full markdown branch in the works, but until that is ready for public use, I think this can be a stand-in to make life more workable in certain cases.
Changes:
- A `*` that would normally start _italics_ but isn't matched by a closing `*`, is now left alone.
- A `` ` `` that would normally start a `code block` but isn't matched by a closing `` ` ``, is now left alone.
- Backslashes `\` should work as expected.
- Bold with `**` and italics with `_` are now also supported.
Fixes #111

Better half-markdown

---

matrix/colors.py
tests/color_test.py

This fixes a bug in my earlier PR #202: backslashes were not properly kept in code blocks. After this fix, they are.
Edit after second commit: markdown parsing is less trivial than I thought, thanks to dkasak for suggesting this needed more tests... :)

Don't parse backslashes in code blocks

---

matrix/commands.py
matrix/completion.py
matrix/utils.py

If a message replied to had a `"` in the first part that is quoted when using `/redact` or `/reply-matrix`, the parsing mechanism in `parse_redact_args` got confused and thought the snippet ended at the first `"`, which was actually part of the message quoted.
This adds some backslashes so that this confusion does not happen anymore.

Allow quotes in replied-to messages

---

matrix/colors.py

Previously, the behaviour was inconsistent; if there was no other formatting, weechat-matrix doesn't send `formatted_body`, and Riot would display the message as-is. If there _was_ other formatting, `formatted_body` is sent without escaping of the HTML characters, so that Riot would interpret them as HTML.
This makes both cases consistent, using the first behaviour.

Escape manually entered html characters

---

matrix/colors.py

This turns off handling of backslash escapes and `*`/`**`/`_` wrappers. Code blocks with `` ` `` continue to work as they did, to allow stuff like "`ftp://url_ends`here", without a space before the `h`.
Additionally, IRC formatting bytes always work, to allow people's scripts/plugins to remain working as they did. (I think it was said somewhere that this is why the parser supports IRC formatting bytes in the first place.)

Don't process markdown in URL's

---

matrix/buffer.py

This allows setting key bindings specifically for matrix buffers. As discussed on #weechat-matrix.
It doesn't seem to break anything for me.

Namespace buffers with "matrix."

---

Makefile

This fixes #222 
Uses [order-only prerequisites](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types) in the makefile to signal that the directory needs to be created only once before anything that depends on the directory existing.

Tinker with makefile to avoid directory-file race conditions

---

README.md
main.py
matrix/buffer.py
matrix/commands.py
matrix/globals.py

This allows using middleclick-R to reply to a particular message.
The key is never unbound by the script. This is also [wee-slack](https://github.com/wee-slack/wee-slack/#cursor-and-mouse-mode)'s behaviour. It was discussed in #weechat-matrix that we can possibly copy this.

Reply using 'r' in cursor mode

---

matrix/_weechat.py
matrix/colors.py
matrix/config.py
tests/color_test.py

As requested in #weechat-matrix around 2020-08-25 20:30 UTC, this adds a config option that toggles whether or not markdown is parsed in chat message input. The config option is set to true by default, because:
1. this is currently the expected behaviour; setting it to off by default would be a breaking change
2. if people didn't like it, more would have complained before now; as it is, I know of only one person.
If the option is set to false, some of the preprocessing code and url-protecting code still runs, even though it doesn't end up doing anything useful. If this is considered a performance issue, I do not see a better option than creating a partial copy of the `from_input_line` function that only does IRC format char parsing; I did not do this yet in the interest of DRY.

Toggle markdown parsing with matrix.look.markdown_input

---

README.md

If you just copy and paste the current "/python version" command from the docs, you will have a leading whitespace character which Weechat will not like.

Fix leading whitespace in "/python version" command

---

matrix/buffer.py

As title says; exposes canonical alias for a room with `/buffer localvar`
credit @spinward

buffer: Expose canonical_alias as localvar in buffer

---

contrib/matrix_decrypt.py

I recently tried to use `matrix_decrypt.py`, but found its usage a bit odd. I generally wanted to save attachments to a known path, not to "run" them with something.
As such I added a second (optional) positional argument to specify a destination file. If a path has been specified, we just save without running the default plumber.
Running with a single argument runs the plumber as before, and specifying a custom plumber allows to both save and run the plumber.
In the second commit I change the default plumber from "rifle" to "xdg-open". Despite loving ranger, IMHO xdg-open is something which is a bit more useful for the general public.

Tweaks to contrib/matrix_decrypt.py

---

matrix/server.py

Previously, once there's one response error, it's impossible to fetch any more backlog.
That bug might be the cause of #213 .
------
I'm not sure what's the best place to put it; or if there's any type of error (handled by that code) not caused by fetching backlog. The callbacks make it *really* hard to see what the program will execute next.

Set backlog_pending to false on error

---

matrix/buffer.py

The configured warning sign previously only applied to the bar.

Use the configured encryption warning sign in the buffer prefix

---

requirements.txt

From #python on Freenode IRC network:
> 09:04:44 graingert | strk: you should probably remove that requirement, it's outdated
> 09:05:24 graingert | Or change it to `future; python_version < '3.2'`

Only require 'future' for python <3.2

---

matrix/colors.py

This indexing (i.e. `__getitem__`) introduced in Python 3.5 as an alias of
the group method, so using it breaks this plugin on older Python
versions. In particular, messages containing urls cannot be sent and
result in an exception:
File "matrix/colors.py", line 106, in <lambda>
lambda m: "a" * len(m[0]),
TypeError: '_sre.SRE_Match' object has no attribute '__getitem__'
This commit replaces the use of the index operation / `__getitem__` with
the group method, which is equivalent but supported on all python
versions.

colors: Do not use [] indexing on re.match objects

---

matrix/buffer.py

Adds support for [Heisenbridge](https://github.com/hifi/heisenbridge) IRC bridge short names for any network.
I know it's a niche bridge but I'm also slightly annoyed I need to manually patch this in all the time :sweat_smile: 
The full ID format is `@irc_network_nick` and for increased accuracy we could test it against a regex to prevent accidental naming issues but I'm not sure if it's worth the effort.
In the Rust version it would probably be more correct to have configuration settings so you can set this per homeserver where you know what prefix is reserved for which bridge and have defaults in that match what matrix.org is known to be running.

Support Heisenbridge short names

---

contrib/matrix_upload.py

Calling ``matrix_upload.py --encrypt`` with a filename outside of the
current directory fails due to a typo in EncryptedUpload which uses the
basename of the file instead of the original/full path.

Use the full path when reading in EncryptedUpload

---

matrix/commands.py

I've encountered a problem when trying to use a passphrase with spaces in `/olm import`.
The arguments were just broken by spaces. shlex has more advanced splitting which allows
taking multi-word arguments in quotes.

Support quoting for command arguments

---

README.md

Matrix-decryptapp is a client-side web app to decrypt and open encrypted matrix files directly in the browser.
See background information here: https://github.com/seirl/matrix-decryptapp

README: mention decryptapp as an alternative to open emxc:// URLs

---

matrix/server.py

This function is deprecated in favour of `set_alpn_protocols()`, which is already called, and is currently broken in Python 3.10, so remove it altogether.
Closes: #308

server: remove set_npn_protocols()

---

Makefile

WeeChat 3.2 and newer default to `$XDG_DATA_HOME/weechat` (by default this is `~/.local/share/weechat`) unless `~/.weechat` exists.
Closes #306.

Prefer XDG directory for WeeChat if it exists

---

pyproject.toml

Commit 69cbba8839ad68420d55bd56833eb3e970ee6311 ("Only require 'future' for python <3.2") should be reflected by `pyproject.toml` as well.

pyproject.toml: only require 'future' for python <3.2

---

matrix/buffer.py

I'm using the [mautrix signal bridge](https://github.com/mautrix/signal) hosted on element, and I was not getting display names for signal contacts in weechat. This seems to solve the issue at least on my machine.

buffer: Add signal to display name workarounds.

---

matrix/config.py
requirements.txt

The 0.20.0 made a breaking change in how they handle logging, moving off logbook to the standard logging module, breaking weechat-matrix's config module.
This patch adresses the API change (without migrating ourselves to logboox), and bumps the matrix-nio requirements to reflect the dependency on the new API.

Fix compatibility with matrix-nio 0.21
